name: Update YAML

on:
  issue_comment:
    types: [created]

jobs:
  update-yaml:
    runs-on: ubuntu-latest
    if: github.event.issue.pull_request && contains(github.event.comment.body, '/deploy')
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Fetch PR Base Branch
        id: pr-info
        run: |
          PR_DATA=$(curl -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.issue.number }})
          PR_BASE=$(echo "$PR_DATA" | jq -r .base.ref)
          echo "Base branch of PR: $PR_BASE"
          echo "::set-output name=base_ref::$PR_BASE"

      - name: Checkout Base Branch of PR
        if: steps.pr-info.outputs.base_ref
        run: |
          git fetch origin ${steps.pr-info.outputs.base_ref}:${steps.pr-info.outputs.base_ref}
          git checkout ${steps.pr-info.outputs.base_ref}

      - name: Print Name of Checked Out Branch
        run: |
          branch_name=$(git rev-parse --abbrev-ref HEAD)
          echo "Checked out branch is $branch_name"

