name: Update YAML

on:
  issue_comment:
    types: [created]

jobs:
  update-yaml:
    runs-on: ubuntu-latest
    if: github.event.issue.pull_request && contains(github.event.comment.body, '/deploy')
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Checkout PR Base Branch
        run: |
          PR_DATA=$(curl -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.issue.number }})
          PR_BASE=$(echo "$PR_DATA" | jq -r .base.ref)
          echo "Base branch of PR: $PR_BASE"
          git fetch origin $PR_BASE
          git checkout $PR_BASE

      - name: Print Name of Checked Out Branch
        run: |
          branch_name=$(git rev-parse --abbrev-ref HEAD)
          echo "Checked out branch is $branch_name"
